### ISSUE TITLE
NOUW not calculating properly

### ISSUE THREAD

**Issue by Luburic** [Clean-CaDET/platform#88]
The value of NOUW for _https://github.com/MonoGame/MonoGame/tree/4802d00db04dc7aa5fe07cd2d908f9a4b090a4fd\\MonoGame.Framework\Platform\Audio\OpenAL.cs#L762-L785_ is 0, where we would expect a higher number.

Similar examples:
- https://github.com/OpenRA/OpenRA/blob/920d00bbae9fa8e62387bbff705ca4bea6a26677/OpenRA.Mods.Cnc/FileFormats/IdxReader.cs#L22-L42
- https://github.com/ppy/osu/tree/2cac373365309a40474943f55c56159ed8f9433c/osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs#L36-L66

**Comment by simsimkic** [comment]
CountNumberOfUniqueWords counts unique words only for SyntaxKind.MethodDeclaration methods (and this does not include constructors SyntaxKind.ConstructorDeclaration).
